import type { Metadata } from "next";
import { Geist, Geist_Mono, Courier_Prime, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { satoshi, instrumentSerif } from "@/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const courierPrime = Courier_Prime({
  variable: "--font-courier-prime",
  weight: "400",
  subsets: ["latin"],
});
const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${courierPrime.variable} ${satoshi.variable} ${instrumentSerif.variable} antialiased bg-transparent`}
      >
        <Header />
        <div className="">
          {children}
        </div>
      </body>
    </html>
  );
}
